### ISSUE TITLE
Creating an 'official' project fork?

### ISSUE THREAD

**Issue by andybak** [zlorf/django-dbsettings#16]
Hi, I'm using your fork as it seemed to be the most active and stable.

Would you be interested in making it the 'official' version? Here's what I propose:

1. Create a Github group called django-dbsettings so the project url would be: https://github.com/django-dbsettings/django-dbsettings. You would obvious be the main member but you could invite anyone else with an active fork to join if you preferred to share the burden
2. Asking sciyoshi to update his README to point at the new project and also assign you as the manager on PyPi

I've done this recently with django-backup and django-admin-tools. I think it's the best way forward when the primary repo for a project is no longer being updated.

Alternatively - you can skip the Github group part if you prefer. I just think it's a nicer long-term strategy - if you cease to be interested in being the primary maintainer then it's much easier to pass the mantel.

**Comment by zlorf** [comment]
2. I'm already maintainer on the PyPi (there were no releases there until I've made my fork). Good idea with asking sciyoshi about README - I'll post him.
1. Well, I'm not interested in making group repo at the moment. But I'll keep this idea in mind for future.

**Comment by andybak** [comment]
Did you hear back from @sciyoshi ?

> I'm not interested in making group repo 

The 'group' part is more so the project can have a nice canonical url that is much less likely to change if or when the role of 'chief maintainer' changes. 

Actually I think the most pressing issues to resolve are the fact that sciyoshi's version is the top result in both Google and in Github's own search. It would definitely encourage usage of this app if those two problems could be resolved.

**Comment by sciyoshi** [comment]
@andybak @zlorf - I'm open to linking to this fork since it seems like the most actively-maintained one. Do you know if anyone from Django might be interested in including plugins such as this one as part of their org on GitHub? That might be the best way in the long run.

**Comment by sciyoshi** [comment]
I've merged up master in sciyoshi/django-dbsettings with the commits from this repo. There were some conflicts due to a change in line endings that I manually resolved. At this point, I've also added @zlorf to the collaborators list so that you can make any changes necessary there (either to continue developing or update the readme). Note that I'm not against continuing to maintain, but I hadn't really received any PRs so I wasn't even aware of this fork.

**Comment by zlorf** [comment]
Thanks a lot!

**Comment by andybak** [comment]
See my recent new confusion over at https://github.com/sciyoshi/django-dbsettings/issues/13

;-)
