### ISSUE TITLE
Increasing max_length of 'value' field 

### ISSUE THREAD

**Issue by andybak** [zlorf/django-dbsettings#17]
I'm using dbsettings to allow editing of HTML snippets that aren't specific to a particular page on the site.

A max_length of 255 is too short in many cases. I'm pondering the best way to handle this:

1. Increase it for everyone. Is there a problem with this? As far as I'm aware - varchar fields only use the amount of storage they need but there is probably some performance or storage cost. My hunch is that it's negligible.

2. Make the base Setting class abstract or swappable so users can tweak this. Seems a bit complicated unless there are other benefits you can see growing from this.

3. Stick to what we've got and I'll fork it. Obviously my least favourite option as I'll need to track changes forever more. However - if you feel that it's especially weird of me to want values longer than 255 then I can see this option might be your preferred one.

**Comment by zlorf** [comment]
I've decided to add optional config ``DBSETTINGS_VALUE_LENGTH``. You can set it to e.g. 500 to get more. Beware though -  if you have already installed dbsettings (run it's migrations), you need to manually alter table schema.
