### ISSUE TITLE
Migrations not included in PyPI download

### ISSUE THREAD

**Issue by johnpaulett** [zlorf/django-dbsettings#18]
Maybe I'm missing something obvious, but I can see the [0001_initial migration](https://github.com/zlorf/django-dbsettings/tree/master/dbsettings/migrations) in the repo, but that directory appears to be missing from the tar.gz on PyPI

```
$ wget https://pypi.python.org/packages/source/d/django-dbsettings/django-dbsettings-0.8.1.tar.gz
$ tar -ztvf django-dbsettings-0.8.1.tar.gz | grep -c migrations
0
```
Is there some packaging issue?  Thanks!

**Comment by zlorf** [comment]
Thanks for spotting problem and for patch! I'll release new version to PyPI this weekend.
