### ISSUE TITLE
dbsettings 0.8.2 not compatible with Django 1.9

### ISSUE THREAD

**Issue by soerenbe** [zlorf/django-dbsettings#26]
Django 1.9 removes the url templatetag from the future library. See:

https://docs.djangoproject.com/en/1.9/releases/1.9/#features-removed-in-1-9

Unfortunately this is used in [dbsettings/templates/dbsettings/site_settings.html](https://github.com/zlorf/django-dbsettings/blob/master/dbsettings/templates/dbsettings/site_settings.html). My project worked again, after I deleted this line. I don't know if this have any side effects. I hope just removing this line will work.

It would be great if you update the Pypi Modul.

**Comment by soerenbe** [comment]
I found another issue mentioned in the Changelog above:

**django.db.models.signals.pre_syncdb** and **django.db.models.signals.post_syncdb** is removed.

They are used by the manament command.

**Comment by zlorf** [comment]
Yep, there is already a PR prepared.
I'll merge it and fix issues during Xmas.

**Comment by soerenbe** [comment]
Great! Thanks for your effort.

**Comment by zlorf** [comment]
https://pypi.python.org/pypi/django-dbsettings/0.9.0 have been released.
