### ISSUE TITLE
Choice settings?

### ISSUE THREAD

**Issue by etanter** [zlorf/django-dbsettings#31]
Hi,

Many of the settings in my current application (which does not use db settings yet!) are choices, eg:

```
FOO_CHOICES = (
    (u'OK', 'Approved'),
    (u'FAIL', 'Rejected'),
)
```

I don't see any choice-like setting in the value types. I understand that this might be because there is no obvious mapping to primitive values to put in the database.

The most crazy solution I can think of is to use a String setting with the content `"((u'OK', 'Approved'), (u'FAIL', 'Rejected'),)"` and then use `eval` to get the dictionary back. This is of course a bit violent and risky.

What would you recommend?

Thanks!

**Comment by etanter** [comment]
looking under the hood, I see that all setting values are anyway stored as strings in the DB, so I assume there's some call to eval after looking up settings. The interesting thing though would be to define a value class that exposes a clean form to define a choice, so that it's not arbitrary string getting in the DB.

**Comment by zlorf** [comment]
There is a `choice` argument for the `Values` (mentioned in the docs). Have you tried it?
Something like `PositiveIntegerValue('Foo', choices=((1, 'Rejected'), (2, 'Approved')))`

**Comment by etanter** [comment]
That's not what I'm after, unfortunately. What you're mentioning is for "a setting that is a choice", while in my case it's "a choice that is a setting". 

More precisely, my django app is in fact a mini-product line, and some customization are "bootstrap-time" settings like, things set in settings.py, and choices or defaults used in a model field. 
eg.
```
class MyModel ...
   foo = Field....(...choice=<get this from a setting!>)
```
After much fighting I managed to implement what I needed, which supports a "bootstrap-time" use of your framework through a direct DB access API (can't use models, because some of these settings must be accessed during the initial execution of settings.py even).

If you are interested I can describe more what I did and you can consider whether that's a use case you're interested in supporting (and you can surely come up with a better design for it). 

Thanks!

**Comment by zlorf** [comment]
Ah, I see now.
I worry that this choices-from-settings are only "bootstrap-time" and updating them (via dbsettings editor) after application is running don't cause updates in models, does it? Because choices of model field are being stored at startup and cannot be modified later?

**Comment by etanter** [comment]
That's right, changes in these require restarting the application.
