### ISSUE TITLE
non-required integer value raises error

### ISSUE THREAD

**Issue by etanter** [zlorf/django-dbsettings#32]
Hi,

I have a `dbsettings.PositiveIntegerValue(required=False)`

In the settings edition page, it is impossible to save changes if the above setting is left untouched. It raises: `int() argument must be a string or a number, not 'NoneType'`

Is this a bug or am I missing something?

Thanks!

**Comment by zlorf** [comment]
Seems like a bug, I'll check this and repair if confirmed. Thanks for reporting it here!
