### ISSUE TITLE
migrate or syncdb warning on dbsettings 0.9.3 and django 1.8.5?

### ISSUE THREAD

**Issue by GustJc** [zlorf/django-dbsettings#35]
On Django 1.8.5 and dbsettings 0.9.3, I can't create the fields.

For testing purposes I used this on my **core.models.py**
```
import dbsettings

class EmailOptions(dbsettings.Group):
    enabled = dbsettings.BooleanValue('whether to send emails or not')
    sender = dbsettings.StringValue('address to send emails from')
    subject = dbsettings.StringValue(default='SiteMail')

email = EmailOptions()       
```

After migrate, the table exists in the database but the values are never populated.
If I try to run migrate again or syncdb it raises an error:

```
The following content types are stale and need to be deleted:

    core | 

Any objects related to these content types by a foreign key will also
be deleted. Are you sure you want to delete these content types?
If you're unsure, answer 'no'.

    Type 'yes' to continue, or 'no' to cancel: 
```
Either yes or no does nothing.

```
# select * from dbsettings_setting;
 id | module_name | class_name | attribute_name | value 
----+-------------+------------+----------------+-------
(0 rows)
```
Does anyone with django 1.8.5 have the save issue?

**Comment by zlorf** [comment]
`The following content types are stale and need to be deleted` is nothing to worry about.
However, missing settings are strange. When you edit the settings via the admin interface, do they save to database?

**Comment by zlorf** [comment]
EDIT: As far as I remember, settings in database are not created automatically, only when saving a new values. Until then, the default values or `None`s are returned when accessing the settings in code.

**Comment by GustJc** [comment]
You are right, it's just a warning, the settings are all there. I thought the settings page was empty but i must had the models wrong somewhere before.

I'll be changing the name of the thread to  "migrate or syncdb warning on dbsettings 0.9.3 and django 1.8.5?".

Thanks for the help

**Comment by GustJc** [comment]
Closing it as it is a duplicate of #7 now.
