### ISSUE TITLE
DBSETTINGS_VALUE_LENGTH and migrations

### ISSUE THREAD

**Issue by andybak** [zlorf/django-dbsettings#38]
In #17 I suggested using a TextField instead of a CharField for the settings field as the 255 char limit was a major limitation for many use cases.

You suggested instead adding a setting DBSETTINGS_VALUE_LENGTH to allow overriding of max_length.

I've just switched back to using this branch instead of my own fork and I spotted the fact that you use this setting inside the initial migration. Therefore this setting gets 'baked in' to the schema on the first migration. Changing is after that is a bit tricky - anyone doing so would have to set their own MIGRATION_MODULES setting: https://docs.djangoproject.com/en/1.8/ref/settings/#std:setting-MIGRATION_MODULES and become responsible for managing any future migrations.

At the very least this should be documented. People should choose a high-enough DBSETTINGS_VALUE_LENGTH before their first migration to reduce the likelihood of needing a custom MIGRATION_MODULES setting.

**Comment by zlorf** [comment]
There is an easier way - you just need to manually alter SB schema (run SQL query) to lengthen the field. It's mentioned in the README.

**Comment by andybak** [comment]
Manually altering schema sounds like a bad idea to me. How does that fit in with automated deploys, migrations etc?
