### ISSUE TITLE
ForeignKey warning with Django 1.10

### ISSUE THREAD

**Issue by merwok** [zlorf/django-dbsettings#39]
System check identified no issues (0 silenced).
venv/lib/python3.5/site-packages/dbsettings/migrations/0001_initial.py:24:

RemovedInDjango20Warning: on_delete will be a required arg for ForeignKey in Django 2.0. Set it to models.CASCADE on models and in existing migrations if you want to maintain the current default behavior.
See https://docs.djangoproject.com/en/1.10/ref/models/fields/#django.db.models.ForeignKey.on_delete

  ] + ([('site', models.ForeignKey(to='sites.Site'))] if USE_SITES else [])

**Comment by zlorf** [comment]
Fixed.
