### ISSUE TITLE
empty settings page after port

### ISSUE THREAD

**Issue by etanter** [zlorf/django-dbsettings#56]
Hi,

I've been using dbsettings for quite some time, without any issue.

Recently we migrated our django app from python2/django1.11/suit to python3/django2.2/baton, and as an unexpected consequence, the dbsettings page is empty (`pg` is the name of the app):

<img width="271" alt="Screen Shot 2020-06-22 at 3 49 47 AM" src="https://user-images.githubusercontent.com/1315554/85262363-aacf3d80-b43b-11ea-9e4d-b28526cabb94.png">

Apart from that, everything is functional. The dbsettings are accessible programmatically, and appropriately set, etc. It's really just the web interface to the dbsettings that is not working.

Any idea on what could be happening here??

Thanks!

**Comment by etanter** [comment]
By fiddling around with the template files, I found that the problem was in this line in `values.html`:
```
{% regroup class.list|dictsort:"verbose_name" by verbose_name as classes %}
```
I simply removed the `dictsort` stuff and now it works! 
weird?

**Comment by mahdi1008** [comment]
I faced the same problem and i solved it by giving the class constructor a "verbose_name", as below:
```
class SomeSettings(dbsettings.Group):
    # Fields placed here
    pass

options = SomeSettings(verbose_name="some_settings")
```
and when i used it with `options = SomeSettings()`, I faced that empty settings page.

**Comment by ZackPlauche** [comment]
I had the same issue and @mahdi1008 's fix worked. But still, this should be the default behavior even without setting a verbose name.

**Comment by zlorf** [comment]
Sorry for much for the waiting time, but it's finally fixed!
