### ISSUE TITLE
settings/ -  superuser does not have permissions to edit

### ISSUE THREAD

**Issue by cybernamix** [zlorf/django-dbsettings#61]
Django version 3.2.5
Logged in to admin as Superuser but seeing this message when accessing from localhost:8000/settings/ 

"You don't have permission to edit values."

I can visit admin and am logged in. 
If I comment the staff-required decorator in views.py the issue remains

**Comment by sylvoie** [comment]
Hello,

I have the same problem.

Has anyone solved this problem?

Thank's

**Comment by zlorf** [comment]
Have you tried to run `manage.py migrate` in order to install proper permissions to the database? I know that in theory superuser should be able to do anything, but maybe missing permission objects are creating some kind of exception which is interpreted as "no permission to edit value".

**Comment by zlorf** [comment]
It may also mean you don't have any settings defined..?

**Comment by zlorf** [comment]
Yeah, that was the case. With commit 60cb296b10461dbd71b807a972dd41338d92b9d0 I've fixed the incorrect message in case there were no settings.
Please let me know if that helped to solve your case - if you can try out master branch.

**Comment by zlorf** [comment]
@cybernamix, @sylvoie - can you try out the patch and tell me if it solves your issue? If yes, I'd release a new version.

**Comment by sylvoie** [comment]
Hello,

Yes I will try your patch and thank you for your help.

About the command : `manage.py migrate`

> Operations to perform:
>   Apply all migrations: admin, auth, blog, contenttypes, dbsettings, sessions
> Running migrations:
>   No migrations to apply.

**Comment by sylvoie** [comment]
Hello,

Ok, it's confirmed, the message is : No settings were defined.

Thank's
