### ISSUE TITLE
Can't syncdb

### ISSUE THREAD

**Issue by wWolfovich** [zlorf/django-dbsettings#9]
Using python-2.7 and Django-1.7 and django-dbsettings-0.7

I have created options.py in my app with next content
```python
import dbsettings

class GeneralOptions(dbsettings.Group):
    network = dbsettings.StringValue(
        'management network',
        default='192.168.200.0/24',
        help_text='Management network (where cluster nodes live)')


general = GeneralOptions('GeneralOptions')
```
Then I import whole module in my app's models.py, but when I do `./manage.py syncdb` I get error
```
CommandError: System check identified some issues:

ERRORS:
dbsettings.Setting.site: (fields.E300) Field defines a relation with model 'Site', which is either not installed, or is abstract.
```
What I do wrong?

**Comment by zlorf** [comment]
Hi, you must add ``'django.contrib.sites'`` to your ``INSTALLED_APPS``. I've apparently forgotten to include this info in the docs.

**Comment by wWolfovich** [comment]
Ok, thanks.
Maybe stupid question but, does `django.contrib.sites` is realy necessary in your app, may be make it optional? As I understand, django's sites framework only needed if I use single django instance for multiple sites, which I don't.
